---
- name: start docker
  service: name=docker state=started

- name: reload docker
  service: name=docker state=reloaded

- name: restart dockerio
  service: name=docker.io state=restarted

- name: update grub
  command: update-grub

- name: reboot
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: true
  ignore_errors: true
  when: ansible_bios_version != 'VirtualBox'

- name: wait for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=45
  become: false
  when: ansible_bios_version != 'VirtualBox'
